POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "eleonore48@gmail.com",
  "goo_token": "sdfsdfsdfg"
}

###
GET http://localhost:8000/api/user
Authorization: Bearer 26857d33f0fdf7f368c60d39cf2a8aac508663b89c224b0c0dad86962fc208d1
Accept: application/json

###
GET http://127.0.0.1:8000/api/letter-opened/6207d403-828c-335e-b16e-5d1c1a703197
Authorization: Bearer feac22e08ad6244c2678040d47d2c7952c2859df2b11025bca86adb4b7377e65
Accept: application/json

###
POST http://127.0.0.1:8000/api/letters
Accept: application/json
Content-Type: application/json

{
  "email": "eleonore48@gmail.com",
  "recipient": "abbigail@example.org",
  "subject_letter": "dsdfs sdfsf sfs",
  "img_token": "23423efwv23ccsdcc"
}

###
GET http://127.0.0.1:8000/api/letters
Authorization: Bearer 6fa9f046b5f43aa281843199e156ffea09a1f814aca0a244fa626f0c441438b2
Accept: application/json

###
GET http://127.0.0.1:8000/api/health-check
Accept: application/json

<> 2023-03-19T193223.200.json



